### ISSUE TITLE
[FEAT] add useChainGuard hook

### ISSUE THREAD

**Issue by ivelin** [kalidao/hooks#1]
**Is your feature request related to a problem? Please describe.**
When users are connected on one ETH chain they are allowed to submit an on-chain transactions in Kali UI to a Kali DAO that is hosted on a different chain. For example vote or propose tx. The transaction is accepted and the gas fee is paid, but the desired result is not achieved. 

**Describe the solution you'd like**
This React Hook would allow UI pages with contract write transactions to ensure that the user is connected to the same chain where the DAO is hosted.

**Describe alternatives you've considered**
We discussed with @nerderlyne and @audssy the alternative to build visual React components, such as MUI buttons, that have built in chain guard functionality. However that would limit the ability of designers to experiment with different UI component libraries. Hence the decision to expose chain guard logic as a react hook that is independent of visualization libraries.

**Additional context**
Prior work on this topic here:
https://github.com/kalidao/kali-ui/pull/252

**Comment by ivelin** [comment]
Some additional context:

wagmi 0.6.5 [introduced a `chainid` argument](https://wagmi.sh/docs/migration-guide#behavioral-changes-1) to `usePrepareContractWrite` and `useContractWrite` that effectively prevents users from executing a write transaction on the wrong chain. However if use is on the wrong chain, using chainId does not result in a dialog prompting user to switch networks.

> If a chainId is passed to useSendTransaction, it will no longer attempt to switch chain before sending the transaction. Instead, it will throw an error if the user is on the wrong chain.
> 
> Why? Eagerly prompting to switch chain in these actions created a long-running async task that that makes [iOS App Links](https://wagmi.sh/docs/prepare-hooks/intro#ios-app-link-constraints) vulnerable.

**Comment by ivelin** [comment]
UPDATE:

Just noticed that wagmi introduced `useConnect`, which might simplify UX by forcing a switch to the DAO chain Id on submit. Testing it now. Depending on results, it may affect the design of useChainGuard.

**Comment by ivelin** [comment]
It turns out that `useConnect` does not work as I hoped. It cannot be used when the user is already connected to another network. That results in a runtime error:
![Screen Shot 2022-09-19 at 1 24 36 PM](https://user-images.githubusercontent.com/2234901/191090210-f35920c9-6a91-469e-a70d-de6ba47749f7.png)

**Comment by nerderlyne** [comment]
They have useSwitchNetwork for programmatically changing the chain.

**Comment by ivelin** [comment]
> They have useSwitchNetwork for programmatically changing the chain.

Yes, I played with it too, but at this stage it is not 100% reliable. [From the docs](https://wagmi.sh/docs/hooks/useSwitchNetwork):
> Some wallet apps do not support programmatic network switching and switchNetwork will be undefined. For those situations, you can typically switch networks in the wallet app and wagmi will stay up-to-date.
